contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #rsv_ampseq channel"
    url: https://nfcore.slack.com/channels/rsv_ampseq
    about: Discussion about the nf-core/rsv_ampseq pipeline
